import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { NgbDateStruct, NgbCalendar, NgbDate, NgbDatepickerI18n } from '@ng-bootstrap/ng-bootstrap';
import * as i0 from "@angular/core";
export declare class SwireDatepickerComponent implements OnInit, ControlValueAccessor {
    private calendar;
    i18n: NgbDatepickerI18n;
    private _eref;
    myDatePicker: any;
    swireDynamicDatePlaceholder: string;
    swireDynamicClassName: string;
    swireDynamicIconClass: string;
    swireDynamicColorClass: string;
    swireDynamicSizeClass: string;
    label: string;
    swireDynamicMinDate: any;
    swireDynamicMaxDate: any;
    swireDynamicStartDate: any;
    displayMonths: any;
    firstDayOfWeek: any;
    private value;
    disabled: boolean;
    onChange: any;
    onTouch: any;
    hoveredDate: NgbDate | null;
    fromDate: NgbDate;
    toDate: NgbDate | null;
    model: NgbDateStruct;
    date: {
        year: number;
        month: number;
    };
    constructor(calendar: NgbCalendar, i18n: NgbDatepickerI18n, _eref: ElementRef);
    writeValue(obj: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState?(isDisabled: boolean): void;
    dateValueChanged(): void;
    ngOnInit(): void;
    selectToday(): void;
    onDateSelection(date: NgbDate): void;
    isHovered(date: NgbDate): boolean | null;
    isInside(date: NgbDate): boolean | null;
    isRange(date: NgbDate): boolean | null;
    onChangeHandler(e: any): void;
    onTouched: () => void;
    touched: boolean;
    markAsTouched(): void;
    showHideCal: any;
    showHide(): void;
    nullVal: any;
    callFromParent(): void;
    onClick(event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SwireDatepickerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SwireDatepickerComponent, "swire-datepicker", never, { "swireDynamicDatePlaceholder": "swireDynamicDatePlaceholder"; "swireDynamicClassName": "swireDynamicClassName"; "swireDynamicIconClass": "swireDynamicIconClass"; "swireDynamicColorClass": "swireDynamicColorClass"; "swireDynamicSizeClass": "swireDynamicSizeClass"; "label": "label"; "swireDynamicMinDate": "swireDynamicMinDate"; "swireDynamicMaxDate": "swireDynamicMaxDate"; "swireDynamicStartDate": "swireDynamicStartDate"; "displayMonths": "displayMonths"; "firstDayOfWeek": "firstDayOfWeek"; "disabled": "disabled"; "model": "model"; "showHideCal": "showHideCal"; }, {}, never, never>;
}
