import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class SwireInputFilterComponent implements OnInit, ControlValueAccessor {
    private _eref;
    myInput: any;
    filterData: any;
    atleastOneSelected: boolean;
    btnActiveClassName: string;
    btnClassName: string;
    bindLabel: string;
    bindValue: any;
    swireDynamicClassName: string;
    swireDynamicReferenceName: string;
    swireDynamicId: string;
    searchBoxPlaceHolder: string;
    filterdata: any;
    allCheckedItems: any;
    showList: boolean;
    disabled: boolean;
    szValue: any;
    touched: any;
    inputDropdownFilter: ElementRef;
    listDropdownFilter: ElementRef;
    constructor(_eref: ElementRef);
    onClick(event: any): void;
    ngOnInit(): void;
    onChange: (szValue: any) => void;
    onTouched: () => void;
    writeValue(szValue: any): void;
    onChangeHandler(e: any): void;
    registerOnChange(onChange: any): void;
    registerOnTouched(onTouched: any): void;
    markAsTouched(): void;
    setDisabledState(disabled: boolean): void;
    onSelected(item: any): void;
    showHideItems(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SwireInputFilterComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SwireInputFilterComponent, "swire-input-filter", never, { "filterData": "filterData"; "atleastOneSelected": "atleastOneSelected"; "btnActiveClassName": "btnActiveClassName"; "btnClassName": "btnClassName"; "bindLabel": "bindLabel"; "bindValue": "bindValue"; "swireDynamicClassName": "swireDynamicClassName"; "swireDynamicReferenceName": "swireDynamicReferenceName"; "swireDynamicId": "swireDynamicId"; "searchBoxPlaceHolder": "searchBoxPlaceHolder"; }, {}, never, never>;
}
