import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class SwireCheckboxFilterComponent implements OnInit, ControlValueAccessor {
    private _fb;
    private _eref;
    toggleButton: ElementRef | undefined;
    listFilter: ElementRef | undefined;
    myInput: any;
    filterCheckBoxData: any;
    atleastOneSelected: boolean;
    btnName: string;
    btnActiveClassName: string;
    btnClassName: string;
    bindLabel: string;
    bindValue: string;
    swireDynamicClassName: string;
    showSearchBox: boolean;
    buttonClassForColor: string;
    searchBoxPlaceHolder: string;
    dropDownType: string;
    swireDynamicId: string;
    swireDynamicReferenceName: string;
    filterdatas: any;
    inputDropdownFilter: ElementRef;
    isTrue: boolean;
    filterdata: any;
    filterDataCheckbox: any;
    allCheckedItems: any;
    showList: boolean;
    showIndeterminateState: boolean;
    disabled: any;
    szValue: any;
    touched: any;
    onChange: (szValue: any) => void;
    onTouched: () => void;
    writeValue(szValue: any): void;
    onChangeHandler(e: any): void;
    registerOnChange(onChange: any): void;
    registerOnTouched(onTouched: any): void;
    markAsTouched(): void;
    setDisabledState(disabled: boolean): void;
    constructor(_fb: FormBuilder, _eref: ElementRef);
    onClick(event: any): void;
    ngOnInit(): void;
    onSelected(item: any): void;
    focusIn(): void;
    showHideItems(): void;
    selectAll(e: any): void;
    checkExist(val: any): boolean;
    checkAllExist(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<SwireCheckboxFilterComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SwireCheckboxFilterComponent, "swire-checkbox-filter", never, { "filterCheckBoxData": "filterCheckBoxData"; "atleastOneSelected": "atleastOneSelected"; "btnName": "btnName"; "btnActiveClassName": "btnActiveClassName"; "btnClassName": "btnClassName"; "bindLabel": "bindLabel"; "bindValue": "bindValue"; "swireDynamicClassName": "swireDynamicClassName"; "showSearchBox": "showSearchBox"; "buttonClassForColor": "buttonClassForColor"; "searchBoxPlaceHolder": "searchBoxPlaceHolder"; "dropDownType": "dropDownType"; "swireDynamicId": "swireDynamicId"; "swireDynamicReferenceName": "swireDynamicReferenceName"; "filterdatas": "filterdatas"; "showIndeterminateState": "showIndeterminateState"; }, {}, never, never>;
}
